openapi: 3.0.1
info:
  title: Firewall Rule Patcher API
  description: Applies a validated firewall rule to a specified NSG using Azure Function.
  version: "1.0.0"

servers:
  - url: https://firerulepatcherfunction.azurewebsites.net

paths:
  /api/applyrule:
    post:
      operationId: ApplyFirewallRule
      summary: Applies a firewall rule to an NSG
      description: |
        Applies a validated firewall rule to a specified Network Security Group (NSG) using Azure Function.
        # ExamplePrompts
        Apply firewall rule to allow TCP traffic from 0.0.0.0/0 to 10.0.0.4/32 on port 22
      security:
        - azureAD: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                nsg_name:
                  type: string
                rule_name:
                  type: string
                priority:
                  type: integer
                direction:
                  type: string
                  enum: [Inbound, Outbound]
                access:
                  type: string
                  enum: [Allow, Deny]
                protocol:
                  type: string
                  enum: [Tcp, Udp, "*"]
                source:
                  type: string
                destination:
                  type: string
                port:
                  type: string
      responses:
        '200':
          description: Rule applied successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  message:
                    type: string
        '400':
          description: Invalid input parameters
        '500':
          description: Server error

components:
  securitySchemes:
    azureAD:
      type: http
      scheme: bearer
      bearerFormat: JWT
