openapi: 3.0.1
info:
  title: Firewall Rule Patcher API
  version: "1.0.0"
  description: Applies a validated firewall rule to a specified NSG using Azure Function.

servers:
  - url: https://firewallrulepatcherfunction.azurewebsites.net

paths:
  /api/applyrule:
    post:
      operationId: ApplyFirewallRule
      summary: Apply firewall rule
      security:
        - FunctionKey: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - nsg_name
                - rule_name
                - priority
                - direction
                - access
                - protocol
                - source
                - destination
                - port
              properties:
                nsg_name:
                  type: string
                rule_name:
                  type: string
                priority:
                  type: integer
                direction:
                  type: string
                  enum: [Inbound, Outbound]
                access:
                  type: string
                  enum: [Allow, Deny]
                protocol:
                  type: string
                  enum: [Tcp, Udp, "*"]
                source:
                  type: string
                destination:
                  type: string
                port:
                  type: integer
      responses:
        '200':
          description: Rule applied
        '400':
          description: Bad request
        '500':
          description: Internal error

components:
  securitySchemes:
    FunctionKey:
      type: apiKey
      name: code
      in: query
