openapi: 3.0.1
info:
  title: Firewall Rule Patcher API
  version: "1.0.0"
  description: Applies validated firewall rules via Azure Function

servers:
  - url: https://firewallrulepatcherfunction.azurewebsites.net

paths:
  /api/applyrule:
    post:
      summary: Apply firewall rule
      operationId: ApplyFirewallRule
      description: Applies a firewall rule to an NSG
      security:
        - FunctionKey: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - nsg_name
                - rule_name
                - priority
                - direction
                - access
                - protocol
                - source
                - destination
                - port
              properties:
                nsg_name:
                  type: string
                rule_name:
                  type: string
                priority:
                  type: integer
                direction:
                  type: string
                access:
                  type: string
                protocol:
                  type: string
                source:
                  type: string
                destination:
                  type: string
                port:
                  type: string
      responses:
        '200':
          description: Rule applied
        '400':
          description: Bad request
        '500':
          description: Server error

components:
  securitySchemes:
    FunctionKey:
      type: apiKey
      name: x-functions-key
      in: header
