openapi: 3.0.1
info:
  title: Firewall Rule Patcher API
  version: "1.0.0"
  description: Applies firewall rules to NSGs via Azure Function.

servers:
  - url: https://firewallrulepatcherfunction.azurewebsites.net

paths:
  /api/applyrule:
    post:
      operationId: ApplyFirewallRule
      summary: Apply firewall rule
      security:
        - FunctionKey: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - nsg_name
                - rule_name
                - priority
                - direction
                - access
                - protocol
                - source
                - destination
                - port
              properties:
                nsg_name: { type: string }
                rule_name: { type: string }
                priority: { type: integer }
                direction: { type: string }
                access: { type: string }
                protocol: { type: string }
                source: { type: string }
                destination: { type: string }
                port: { type: string }
      responses:
        '200': { description: Success }
        '400': { description: Bad input }
        '500': { description: Server error }

components:
  securitySchemes:
    FunctionKey:
      type: apiKey
      in: header
      name: x-functions-key