openapi: 3.0.1
info:
  title: IP Trust Classifier
  version: "1.0.0"
  description: Classifies IPs using threat intelligence data

servers:
  - url: https://your-function-url.com/api  # Replace with your Azure Function URL

paths:
  /check:
    post:
      operationId: IPTrustClassifier
      summary: Classify an IP address
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                ipAddress:
                  type: string
                  example: "8.8.8.8"
      responses:
        '200':
          description: Classification result
          content:
            application/json:
              schema:
                type: object
                properties:
                  ip:
                    type: string
                  classification:
                    type: string
                  threatScore:
                    type: integer
                  confidence:
                    type: string
        '400':
          description: Invalid input
        '401':
          description: Unauthorized

components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: Key

security:
  - ApiKeyAuth: []