name: FirewallRulePatcher
version: 1.0.0
publisher: your-org
description: Applies firewall rule using Azure REST API

SkillGroups:
  - Format: API
    Skills:
      - Name: Apply
        Description: Applies a validated firewall rule using Azure Function
        Auth:
          Type: None
        InputSchema:
          Type: object
          Properties:
            nsg_name:
              Type: string
              Description: Name of the Network Security Group
            rule_name:
              Type: string
              Description: Name of the rule to apply
            priority:
              Type: integer
              Description: Rule priority
            direction:
              Type: string
              Enum: [Inbound, Outbound]
            access:
              Type: string
              Enum: [Allow, Deny]
            protocol:
              Type: string
              Enum: [Tcp, Udp, "*"]
            source:
              Type: string
              Description: Source IP range
            destination:
              Type: string
              Description: Destination IP range
            port:
              Type: string
              Description: Port range
        Endpoint:
          Url: https://firerulepatcherfunction.azurewebsites.net/api/applyrule
          Method: POST
