openapi: 3.0.0
info:
  title: FirewallRulePatcher
  description: Applies validated rule changes via NSG/Azure Firewall
  version: "1.0.0"
servers:
  - url: https://yourapi.contoso.com  # Replace with your actual base URL
paths:
  /apply-rule:
    post:
      operationId: ApplyFirewallRule
      summary: Apply a validated firewall rule
      description: >
        Applies a firewall rule after validation through Copilot agent workflow.
        #ExamplePrompts Apply rule to allow RDP from 10.0.0.5 to 10.0.1.1
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                sourceIP:
                  type: string
                destIP:
                  type: string
                protocol:
                  type: string
                destPort:
                  type: integer
                action:
                  type: string
                ruleName:
                  type: string
              required: [sourceIP, destIP, protocol, destPort, action, ruleName]
      responses:
        '200':
          description: Rule successfully applied
        '400':
          description: Invalid input
        '401':
          description: Unauthorized
